name: Build Launcher
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
      - name: Build Android
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: Launcher-APK
          path: android/app/build/outputs/apk/release/*.apk
